import logging
import os
from PyQt6.QtWidgets import QMessageBox

PLUGIN_NAME = "Gaussian Input Generator Pro"
PLUGIN_VERSION = "1.0.2"
PLUGIN_AUTHOR = "HiroYokoyama"
PLUGIN_DESCRIPTION = "Advanced Gaussian Input Generator with Preview and Presets."
PLUGIN_CATEGORY = "Export"
PLUGIN_TAGS = ["input generator", "export"]
PLUGIN_DEPENDENCIES = []  # PyQt6/RDKit come from the host app; psutil is optional
PLUGIN_SUPPORTED_MOLEDITPY_VERSION = ">=4.0.0, <5.0.0"
SETTINGS_FILE = os.path.join(os.path.dirname(__file__), "settings.json")


def get_default_settings():
    return {
        "nproc": 4,
        "mem_val": 4,
        "mem_unit": "GB",
        "chk": "",
        "route": "#P B3LYP/6-31G(d) EmpiricalDispersion=GD3BJ Opt Freq",
        "comment": "Generated by MoleditPy Gaussian Input Generator Pro Plugin",
        "tail": "",
        "link1_enabled": False,
        "link1_route": "#P B3LYP/6-31G(d) Freq Geom=Check Guess=Read",
        "link1_title": "Generated by MoleditPy Gaussian Input Generator Pro Plugin",
        "link1_geom_src": "Checkpoint (Geom=Check Guess=Read)",
        "link1_tail": "",
        "oldchk": "",
        "coord_format": "Cartesian (XYZ)",
    }


current_settings = get_default_settings()
_dialog_opened = False  # Guard: don't write to project file until dialog is used
_context = None  # Stored from initialize() so run() can use the context API


def run(mw):
    global _dialog_opened

    # Prefer the stable context API over direct mw access
    if _context is not None:
        mw = _context.get_main_window()

    from .main_dialog import GaussianSetupDialogPro

    mol = None
    try:
        mol = (
            _context.current_molecule
            if _context is not None
            else getattr(mw, "current_mol", None)
        )
    except Exception as e:
        logging.warning("Gaussian plugin: could not get current molecule: %s", e)
        mol = None
    if not mol:
        QMessageBox.warning(mw, PLUGIN_NAME, "No molecule loaded.")
        return

    filename = None
    try:
        if hasattr(mw, "init_manager"):
            filename = getattr(mw.init_manager, "current_file_path", None)
    except Exception as e:
        logging.warning("Gaussian plugin: could not get file path: %s", e)
    if not filename and mw is not None:
        title = mw.windowTitle()
        filename = title.split(" - ")[0].strip() if " - " in title else title.strip()

    if _context is not None:
        dlg = _context.get_window("dialog")
        if dlg is not None and dlg.isVisible():
            dlg.raise_()
            dlg.activateWindow()
            return

    _dialog_opened = True

    def _mark_modified():
        if _context is not None:
            _context.mark_project_modified()

    def _get_molecule():
        if _context is not None:
            return _context.current_molecule
        return getattr(mw, "current_mol", None)

    dlg = GaussianSetupDialogPro(
        parent=mw,
        mol=mol,
        filename=filename,
        persistent_settings=current_settings,
        mark_modified=_mark_modified,
        get_molecule=_get_molecule,
    )
    if _context is not None:
        _context.register_window("dialog", dlg)
    dlg.show()


def initialize(context):
    global _context
    _context = context

    def show_dialog():
        mw = context.get_main_window()
        run(mw)

    context.add_export_action("Gaussian Input...", show_dialog)

    # Register Persistence Handlers
    def on_save():
        # Don't write anything to the project file until the user has
        # actually opened the dialog at least once in this session.
        if not _dialog_opened:
            return None
        return current_settings

    _MOLECULE_KEYS = {"charge", "mult"}

    def on_load(data):
        if isinstance(data, dict) and data:
            # Strip molecule-specific keys that may exist in older project files
            filtered = {k: v for k, v in data.items() if k not in _MOLECULE_KEYS}
            current_settings.update(filtered)
            global _dialog_opened
            _dialog_opened = True

    def on_reset():
        global _dialog_opened
        dlg = context.get_window("dialog")
        if dlg is not None:
            try:
                dlg.close()
            except Exception as e:
                logging.warning(
                    "Gaussian plugin: could not close dialog on reset: %s", e
                )
            else:
                if dlg.isVisible():
                    # dlg.close() triggered closeEvent()'s "Unsaved Changes"
                    # prompt and the user chose Cancel (or Save failed), so
                    # the dialog is still open and still editing this
                    # document's data. Clearing current_settings / flipping
                    # _dialog_opened off here would silently disconnect the
                    # still-open dialog's future saves from the project file
                    # (on_save() gates on _dialog_opened). Defer the reset.
                    logging.info(
                        "Gaussian plugin: document reset deferred — dialog "
                        "close was cancelled by the user"
                    )
                    return

        _dialog_opened = False
        current_settings.clear()
        current_settings.update(get_default_settings())

    context.register_save_handler(on_save)
    context.register_load_handler(on_load)
    context.register_document_reset_handler(on_reset)
