import os
import json
import re
from PyQt6.QtWidgets import (
    QDialog,
    QVBoxLayout,
    QHBoxLayout,
    QScrollArea,
    QWidget,
    QGroupBox,
    QFormLayout,
    QSpinBox,
    QPushButton,
    QLabel,
    QTextEdit,
    QLineEdit,
    QComboBox,
    QSizePolicy,
    QMessageBox,
    QFileDialog,
    QInputDialog,
    QCheckBox,
)
from PyQt6.QtGui import QFont, QPalette, QColor, QKeySequence, QShortcut
from PyQt6.QtCore import Qt

from rdkit import Chem
from rdkit.Chem import rdMolTransforms

from .highlighter import GaussianSyntaxHighlighter
from .keyword_builder import GaussianRouteBuilderDialog, parse_modredundant_line
from .constants import TAIL_TEMPLATES
from . import PLUGIN_NAME, PLUGIN_VERSION, SETTINGS_FILE
import logging


# Priority order used for auto-suffix detection (first match wins).
_AUTO_SUFFIX_RULES = [
    ("-ts", lambda kw: "OPT=(TS" in kw or "OPT=TS" in kw),
    ("-irc", lambda kw: "IRC" in kw),
    ("-scan", lambda kw: "MODREDUNDANT" in kw),
    ("-opt", lambda kw: re.search(r"\bOPT\b", kw) is not None),
    ("-freq", lambda kw: re.search(r"\bFREQ\b", kw) is not None),
    ("-td", lambda kw: re.search(r"\bTD\b", kw) is not None or "TD=" in kw),
    ("-nmr", lambda kw: "NMR" in kw),
    ("-sp", lambda kw: True),
]


class GaussianSetupDialogPro(QDialog):
    """
    Gaussian Input Generator Pro
    """

    def __init__(
        self,
        parent=None,
        mol=None,
        filename=None,
        persistent_settings=None,
        mark_modified=None,
        get_molecule=None,
    ):
        super().__init__(parent)
        self.setWindowTitle(f"{PLUGIN_NAME} v{PLUGIN_VERSION}")
        self.resize(1100, 800)
        self.setWindowFlags(self.windowFlags() | Qt.WindowType.WindowMinMaxButtonsHint)
        self.setSizeGripEnabled(True)
        self.mol = mol
        self.filename = filename
        self.persistent_settings = persistent_settings
        self.mark_modified = mark_modified
        self.get_molecule = get_molecule
        self.current_inp_file = None  # path of the .gjf file last saved/opened
        self._saved_inp_content = None  # content at last save (for dirty detection)
        self._current_content = ""  # cached output of the most recent generate
        self.ui_ready = False
        self.setup_ui()
        ctrl_s = QShortcut(QKeySequence.StandardKey.Save, self)
        ctrl_s.activated.connect(self._on_ctrl_s)
        self.load_presets_from_file()
        self.load_persistent_settings()
        self.calc_initial_charge_mult()
        self.ui_ready = True
        self.update_preview()  # earlier calls no-op'd while ui_ready was False

    # ------------------------------------------------------------------
    # UI construction
    # ------------------------------------------------------------------

    def setup_ui(self):
        main_layout = QVBoxLayout()

        content_layout = QHBoxLayout()

        # --- Left Side: Settings (Scrollable) ---
        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        scroll_area.setFrameShape(QScrollArea.Shape.NoFrame)

        settings_container = QWidget()
        settings_layout = QVBoxLayout(settings_container)

        # --- Preset Management ---
        preset_group = QGroupBox("Preset Management")
        preset_layout = QHBoxLayout()
        self.preset_combo = QComboBox()
        self.preset_combo.currentIndexChanged.connect(self.apply_selected_preset)
        preset_layout.addWidget(QLabel("Preset:"))
        preset_layout.addWidget(self.preset_combo, 1)
        self.btn_save_preset = QPushButton("Save New...")
        self.btn_save_preset.clicked.connect(self.save_preset_dialog)
        preset_layout.addWidget(self.btn_save_preset)
        self.btn_del_preset = QPushButton("Delete")
        self.btn_del_preset.clicked.connect(self.delete_preset)
        preset_layout.addWidget(self.btn_del_preset)
        preset_group.setLayout(preset_layout)
        settings_layout.addWidget(preset_group)

        # --- Title ---
        title_group = QGroupBox("Title")
        title_layout = QVBoxLayout()
        self.comment_edit = QLineEdit(
            "Generated by MoleditPy Gaussian Input Generator Pro Plugin"
        )
        self.comment_edit.textChanged.connect(self.update_preview)
        title_layout.addWidget(self.comment_edit)
        title_group.setLayout(title_layout)
        settings_layout.addWidget(title_group)

        # --- Link 0 ---
        link0_group = QGroupBox("Link 0 Commands")
        link0_layout = QFormLayout()

        res_h1 = QHBoxLayout()
        self.nproc_spin = QSpinBox()
        self.nproc_spin.setRange(1, 128)
        self.nproc_spin.setValue(4)
        self.nproc_spin.valueChanged.connect(self.update_preview)
        btn_auto_proc = QPushButton("Auto")
        btn_auto_proc.setFixedWidth(50)
        btn_auto_proc.clicked.connect(self.auto_detect_nproc)
        res_h1.addWidget(self.nproc_spin)
        res_h1.addWidget(btn_auto_proc)
        link0_layout.addRow("Processors (%nprocshared):", res_h1)

        res_h2 = QHBoxLayout()
        self.mem_spin = QSpinBox()
        self.mem_spin.setRange(1, 999999)
        self.mem_spin.setValue(4)
        self.mem_spin.valueChanged.connect(self.update_preview)
        self.mem_unit = QComboBox()
        self.mem_unit.addItems(["GB", "MB", "MW"])
        self.mem_unit.currentIndexChanged.connect(self.update_preview)
        btn_auto_mem = QPushButton("Auto")
        btn_auto_mem.setFixedWidth(50)
        btn_auto_mem.clicked.connect(self.auto_detect_mem)
        res_h2.addWidget(self.mem_spin)
        res_h2.addWidget(self.mem_unit)
        res_h2.addWidget(btn_auto_mem)
        link0_layout.addRow("Memory (%mem):", res_h2)

        self.chk_edit = QLineEdit()
        self.chk_edit.setPlaceholderText("auto-generated from filename")
        self.chk_edit.textChanged.connect(self.update_preview)
        link0_layout.addRow("Checkpoint (%chk):", self.chk_edit)

        self.oldchk_edit = QLineEdit()
        self.oldchk_edit.setPlaceholderText("optional %oldchk source")
        self.oldchk_edit.textChanged.connect(self.update_preview)
        link0_layout.addRow("Old Checkpoint (%oldchk):", self.oldchk_edit)

        link0_group.setLayout(link0_layout)
        settings_layout.addWidget(link0_group)

        # --- Route ---
        kw_group = QGroupBox("Route Section (#)")
        kw_layout = QVBoxLayout()
        kw_h_layout = QHBoxLayout()
        self.keywords_edit = QTextEdit(
            "#P B3LYP/6-31G(d) EmpiricalDispersion=GD3BJ Opt Freq"
        )
        self.keywords_edit.setFixedHeight(70)
        self.keywords_edit.textChanged.connect(self.update_preview)
        self.kw_highlighter = GaussianSyntaxHighlighter(self.keywords_edit.document())
        self.btn_route = QPushButton("Builder...")
        self.btn_route.clicked.connect(self.open_keyword_builder)
        kw_h_layout.addWidget(self.keywords_edit)
        kw_h_layout.addWidget(self.btn_route)
        kw_layout.addWidget(QLabel("Route:"))
        kw_layout.addLayout(kw_h_layout)
        kw_group.setLayout(kw_layout)
        settings_layout.addWidget(kw_group)

        # --- Molecular Specification ---
        mol_group = QGroupBox("Molecular Specification")
        mol_layout = QHBoxLayout()
        self.charge_spin = QSpinBox()
        self.charge_spin.setRange(-10, 10)
        self.charge_spin.valueChanged.connect(self.validate_charge_mult)
        self.mult_spin = QSpinBox()
        self.mult_spin.setRange(1, 10)
        self.mult_spin.valueChanged.connect(self.validate_charge_mult)
        mol_layout.addWidget(QLabel("Charge:"))
        mol_layout.addWidget(self.charge_spin)
        mol_layout.addWidget(QLabel("Mult:"))
        mol_layout.addWidget(self.mult_spin)
        self.default_palette = self.charge_spin.palette()
        mol_group.setLayout(mol_layout)
        settings_layout.addWidget(mol_group)

        # --- Coordinate Format ---
        coord_group = QGroupBox("Coordinate Format")
        coord_layout = QVBoxLayout()
        self.coord_format_combo = QComboBox()
        self.coord_format_combo.addItems(
            [
                "Cartesian (XYZ)",
                "Z-Matrix",
                "Z-Matrix (variables)",
            ]
        )
        self.coord_format_combo.currentIndexChanged.connect(self.update_preview)
        coord_layout.addWidget(self.coord_format_combo)
        coord_group.setLayout(coord_layout)
        settings_layout.addWidget(coord_group)

        # --- Tail / Additional Input ---
        tail_group = QGroupBox("Tail / Additional Input")
        tail_layout = QVBoxLayout()
        tail_h = QHBoxLayout()
        self.tail_template_combo = QComboBox()
        self.tail_template_combo.addItem("Select Example Template...")
        self.tail_template_combo.addItems(list(TAIL_TEMPLATES.keys()))
        tail_h.addWidget(self.tail_template_combo, 1)
        self.btn_insert_tail = QPushButton("Insert")
        self.btn_insert_tail.clicked.connect(self.insert_tail_template)
        tail_h.addWidget(self.btn_insert_tail)
        tail_layout.addLayout(tail_h)
        self.tail_edit = QTextEdit()
        self.tail_edit.setFixedHeight(100)
        self.tail_edit.setPlaceholderText(
            "ModRedundant, Gen/GenECP basis, $NBO, connectivity, etc."
        )
        self.tail_edit.textChanged.connect(self.update_preview)
        tail_layout.addWidget(self.tail_edit)
        tail_group.setLayout(tail_layout)
        settings_layout.addWidget(tail_group)

        # --- Additional Job (--Link1--) ---
        link1_group = QGroupBox("Additional Job (--Link1--)")
        link1_outer = QVBoxLayout()

        self.link1_enable = QCheckBox("Enable additional Link1 job")
        self.link1_enable.toggled.connect(self._update_link1_ui)
        self.link1_enable.toggled.connect(self.update_preview)
        link1_outer.addWidget(self.link1_enable)

        self.link1_container = QWidget()
        link1_inner = QVBoxLayout(self.link1_container)
        link1_inner.setContentsMargins(0, 4, 0, 0)

        link1_route_group = QGroupBox("Route Section (#)")
        link1_route_layout = QVBoxLayout()
        self.link1_route_edit = QTextEdit("#P B3LYP/6-31G(d) Freq Geom=Check Guess=Read")
        self.link1_route_edit.setFixedHeight(60)
        self.link1_route_edit.textChanged.connect(self.update_preview)
        self.link1_highlighter = GaussianSyntaxHighlighter(
            self.link1_route_edit.document()
        )
        link1_route_layout.addWidget(self.link1_route_edit)
        link1_route_group.setLayout(link1_route_layout)
        link1_inner.addWidget(link1_route_group)

        link1_form = QFormLayout()
        self.link1_title_edit = QLineEdit(
            "Generated by MoleditPy Gaussian Input Generator Pro Plugin"
        )
        self.link1_title_edit.textChanged.connect(self.update_preview)
        link1_form.addRow("Title:", self.link1_title_edit)

        self.link1_geom_src = QComboBox()
        self.link1_geom_src.addItems(
            ["Checkpoint (Geom=Check Guess=Read)", "Copy coordinates"]
        )
        self.link1_geom_src.currentIndexChanged.connect(self.update_preview)
        link1_form.addRow("Geometry source:", self.link1_geom_src)
        link1_inner.addLayout(link1_form)

        link1_tail_group = QGroupBox("Tail (Job 2)")
        link1_tail_layout = QVBoxLayout()
        self.link1_tail_edit = QTextEdit()
        self.link1_tail_edit.setFixedHeight(60)
        self.link1_tail_edit.textChanged.connect(self.update_preview)
        link1_tail_layout.addWidget(self.link1_tail_edit)
        link1_tail_group.setLayout(link1_tail_layout)
        link1_inner.addWidget(link1_tail_group)

        self.link1_container.setVisible(False)
        link1_outer.addWidget(self.link1_container)
        link1_group.setLayout(link1_outer)
        settings_layout.addWidget(link1_group)

        settings_layout.addStretch()
        scroll_area.setWidget(settings_container)
        content_layout.addWidget(scroll_area, 3)

        # --- Right Side: Preview ---
        preview_group = QGroupBox("Input Preview")
        preview_layout = QVBoxLayout()
        self.preview_text = QTextEdit()
        self.preview_text.setReadOnly(False)
        self.preview_text.setFont(QFont("Courier New", 10))
        self.preview_text.setSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding
        )
        self.highlighter = GaussianSyntaxHighlighter(self.preview_text.document())
        preview_layout.addWidget(self.preview_text)
        btn_refresh = QPushButton("Reset/Refresh Preview")
        btn_refresh.clicked.connect(self.update_preview)
        preview_layout.addWidget(btn_refresh)
        preview_group.setLayout(preview_layout)
        content_layout.addWidget(preview_group, 4)

        main_layout.addLayout(content_layout)

        cb_layout = QHBoxLayout()
        cb_layout.addStretch()
        self.auto_suffix_cb = QCheckBox("Auto Suffix")
        self.auto_suffix_cb.setChecked(True)
        self.auto_suffix_cb.stateChanged.connect(self.update_preview)
        self.auto_suffix_cb.stateChanged.connect(self.save_global_settings)
        cb_layout.addWidget(self.auto_suffix_cb)
        main_layout.addLayout(cb_layout)

        btn_layout = QHBoxLayout()
        self.btn_close = QPushButton("Close")
        self.btn_close.clicked.connect(self.reject)
        self.btn_close.setStyleSheet("padding: 8px; font-size: 14px;")
        self.btn_close.setSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed
        )

        self.save_btn = QPushButton("Save Gaussian Input File...")
        self.save_btn.clicked.connect(self.save_file)
        self.save_btn.setStyleSheet("font-weight: bold; padding: 8px; font-size: 14px;")
        self.save_btn.setSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed
        )

        btn_layout.addWidget(self.btn_close)
        btn_layout.addWidget(self.save_btn)

        main_layout.addLayout(btn_layout)

        self.setLayout(main_layout)
        self.update_preview()

    # ------------------------------------------------------------------
    # Link1 helpers
    # ------------------------------------------------------------------

    def _update_link1_ui(self):
        self.link1_container.setVisible(self.link1_enable.isChecked())

    def insert_tail_template(self):
        name = self.tail_template_combo.currentText()
        template = TAIL_TEMPLATES.get(name)
        if not template:
            return
        cursor = self.tail_edit.textCursor()
        cursor.insertText(template)
        self.tail_edit.setFocus()

    # ------------------------------------------------------------------
    # Molecule / coordinates
    # ------------------------------------------------------------------

    def _resolve_live_mol(self):
        """Prefer the currently active molecule via the context API callback."""
        try:
            if self.get_molecule is not None:
                live = self.get_molecule()
            else:
                live = getattr(self.parent(), "current_mol", None)
            if live is not None:
                self.mol = live
        except Exception as _e:
            logging.warning("_resolve_live_mol failed: %s", _e)
        return self.mol

    def get_coords_lines(self):
        if not self._resolve_live_mol():
            return []
        lines = []
        try:
            conf = self.mol.GetConformer()
            for i in range(self.mol.GetNumAtoms()):
                pos = conf.GetAtomPosition(i)
                atom = self.mol.GetAtomWithIdx(i)
                symbol = (
                    atom.GetProp("custom_symbol")
                    if atom.HasProp("custom_symbol")
                    else atom.GetSymbol()
                )
                lines.append(
                    f"{symbol: <4} {pos.x: >12.6f} {pos.y: >12.6f} {pos.z: >12.6f}"
                )
        except Exception as e:
            return [f"# Error: {e}"]
        return lines

    def _build_zmatrix_data(self):
        """Build Z-matrix connectivity and internal-coordinate values.

        Returns a list of {"symbol", "refs" (0-based), "values"} dicts,
        one per atom, or None when no molecule is available.
        """
        if not self._resolve_live_mol():
            return None
        atoms = list(self.mol.GetAtoms())
        conf = self.mol.GetConformer()

        defined = []
        z_data = []

        for i, atom in enumerate(atoms):
            symbol = (
                atom.GetProp("custom_symbol")
                if atom.HasProp("custom_symbol")
                else atom.GetSymbol()
            )

            if i == 0:
                z_data.append({"symbol": symbol, "refs": [], "values": []})
                defined.append(i)
                continue

            neighbors = [n.GetIdx() for n in atom.GetNeighbors()]
            candidates = [n for n in neighbors if n in defined]
            if not candidates:
                candidates = defined[:]

            refs = [candidates[-1] if candidates else 0]
            candidates_2 = [x for x in defined if x != refs[0]]
            if candidates_2:
                refs.append(candidates_2[-1])
            candidates_3 = [x for x in defined if x not in refs]
            if candidates_3:
                refs.append(candidates_3[-1])

            row = {"symbol": symbol, "refs": [], "values": []}
            if len(refs) >= 1:
                row["refs"].append(refs[0])
                row["values"].append(rdMolTransforms.GetBondLength(conf, i, refs[0]))
            if len(refs) >= 2:
                row["refs"].append(refs[1])
                row["values"].append(
                    rdMolTransforms.GetAngleDeg(conf, i, refs[0], refs[1])
                )
            if len(refs) >= 3:
                row["refs"].append(refs[2])
                row["values"].append(
                    rdMolTransforms.GetDihedralDeg(conf, i, refs[0], refs[1], refs[2])
                )

            z_data.append(row)
            defined.append(i)

        return z_data

    def get_zmatrix_lines(self, use_variables=False):
        """Generate Gaussian Z-matrix lines (1-based references).

        Plain:      H  1 1.089000  2 109.471000  3 120.000000
        Variables:  H  1 B3  2 A3  3 D3   ...   Variables: / B3=1.089000
        """
        try:
            data = self._build_zmatrix_data()
            if not data:
                return []

            lines = []
            var_lines = []
            for i, row in enumerate(data):
                line = f"{row['symbol']: <4}"
                refs = row["refs"]
                vals = row["values"]
                var_names = ("B", "A", "D")
                for k in range(min(3, len(refs))):
                    if use_variables:
                        name = f"{var_names[k]}{i + 1}"
                        line += f"  {refs[k] + 1: >3} {name}"
                        var_lines.append(f" {name}={vals[k]:.6f}")
                    else:
                        line += f"  {refs[k] + 1: >3} {vals[k]: >11.6f}"
                lines.append(line.rstrip())

            if use_variables and var_lines:
                lines.append("Variables:")
                lines.extend(var_lines)
            return lines
        except Exception as e:
            return [f"! Error generating Z-Matrix: {e}"]

    def _get_active_coord_lines(self):
        """Coordinate lines in the selected format (Cartesian fallback)."""
        combo = getattr(self, "coord_format_combo", None)
        style = combo.currentText() if combo is not None else "Cartesian (XYZ)"
        if "Z-Matrix" in style:
            zmat = self.get_zmatrix_lines(use_variables="variables" in style)
            if zmat and not any("Error" in line for line in zmat):
                return zmat
            # Fall back to Cartesian if Z-matrix generation failed
            return ["! Z-Matrix generation failed; using Cartesian"] + (
                self.get_coords_lines()
            )
        return self.get_coords_lines()

    # ------------------------------------------------------------------
    # Preview / generation
    # ------------------------------------------------------------------

    def update_preview(self):
        if not getattr(self, "ui_ready", False):
            return

        if self.persistent_settings is not None:
            p = self.persistent_settings
            p["nproc"] = self.nproc_spin.value()
            p["mem_val"] = self.mem_spin.value()
            p["mem_unit"] = self.mem_unit.currentText()
            p["chk"] = self.chk_edit.text()
            p["oldchk"] = self.oldchk_edit.text()
            p["route"] = self.keywords_edit.toPlainText()
            p["comment"] = self.comment_edit.text()
            p["tail"] = self.tail_edit.toPlainText()
            p["link1_enabled"] = self.link1_enable.isChecked()
            p["link1_route"] = self.link1_route_edit.toPlainText()
            p["link1_title"] = self.link1_title_edit.text()
            p["link1_geom_src"] = self.link1_geom_src.currentText()
            p["link1_tail"] = self.link1_tail_edit.toPlainText()
            p["coord_format"] = self.coord_format_combo.currentText()

        self._current_content = self.generate_input_content()
        self.preview_text.setText(self._current_content)
        self._update_title()

        if self.mark_modified is not None:
            try:
                self.mark_modified()
            except Exception as _e:
                logging.warning("mark_modified failed: %s", _e)

    def load_persistent_settings(self):
        if not self.persistent_settings:
            return
        self.blockSignals(True)
        try:
            p = self.persistent_settings
            if "nproc" in p:
                self.nproc_spin.setValue(p["nproc"])
            if "mem_val" in p:
                self.mem_spin.setValue(p["mem_val"])
            if "mem_unit" in p:
                self.mem_unit.setCurrentText(p["mem_unit"])
            if "chk" in p:
                self.chk_edit.setText(p["chk"])
            if "oldchk" in p:
                self.oldchk_edit.setText(p["oldchk"])
            if "route" in p:
                self.keywords_edit.setText(p["route"])
            if "comment" in p:
                self.comment_edit.setText(p["comment"])
            if "tail" in p:
                self.tail_edit.setPlainText(p["tail"])
            if "link1_enabled" in p:
                self.link1_enable.setChecked(p["link1_enabled"])
            if "link1_route" in p:
                self.link1_route_edit.setPlainText(p["link1_route"])
            if "link1_title" in p:
                self.link1_title_edit.setText(p["link1_title"])
            if "link1_geom_src" in p:
                self.link1_geom_src.setCurrentText(p["link1_geom_src"])
            if "link1_tail" in p:
                self.link1_tail_edit.setPlainText(p["link1_tail"])
            if "coord_format" in p:
                self.coord_format_combo.setCurrentText(p["coord_format"])
            self._update_link1_ui()
        finally:
            self.blockSignals(False)

    def auto_detect_nproc(self):
        cpus = None
        try:
            import psutil

            cpus = psutil.cpu_count(logical=False)
        except Exception:
            pass
        if cpus is None:
            cpus = os.cpu_count()
        if cpus:
            self.nproc_spin.setValue(cpus)

    def auto_detect_mem(self):
        total_mb = 8000
        try:
            import psutil

            total_mb = psutil.virtual_memory().total // (1024 * 1024)
        except Exception as _e:
            logging.warning("auto_detect_mem failed: %s", _e)

        rec_mb = int(total_mb * 0.80)
        self.mem_unit.setCurrentText("MB")
        self.mem_spin.setValue(max(500, rec_mb))

    # ------------------------------------------------------------------
    # Input generation
    # ------------------------------------------------------------------

    def _mem_line(self):
        return f"%mem={self.mem_spin.value()}{self.mem_unit.currentText()}"

    def _wfn_filename_hint(self):
        base = "job"
        if self.filename:
            raw = self.filename.replace("\\", "/").split("/")[-1]
            b = os.path.splitext(raw)[0].lstrip("_")
            if b:
                base = b
        return base

    def generate_input_content(self):
        """Generates the full content of the input file as a string."""
        charge = self.charge_spin.value()
        mult = self.mult_spin.value()

        lines = []
        lines.append(f"%nprocshared={self.nproc_spin.value()}")
        lines.append(self._mem_line())

        oldchk = self.oldchk_edit.text().strip()
        if oldchk:
            lines.append(f"%oldchk={oldchk}")

        chk = self.chk_edit.text().strip()
        if not chk:
            chk = f"{self._wfn_filename_hint()}.chk"
        if not chk.endswith(".chk"):
            chk += ".chk"
        lines.append(f"%chk={chk}")

        route_line = self.keywords_edit.toPlainText().strip()
        if not route_line.startswith("#"):
            route_line = "# " + route_line
        lines.append(route_line)
        lines.append("")

        title = self.comment_edit.text().strip() or "Gaussian Job"
        lines.append(title)
        lines.append("")

        lines.append(f"{charge} {mult}")

        coord_lines = self._get_active_coord_lines()
        if any("Error" in line for line in coord_lines):
            err = "\n".join(line for line in coord_lines if "Error" in line)
            return f"# Error generating coordinates: {err}"
        lines.extend(coord_lines)
        lines.append("")

        tail = self.tail_edit.toPlainText().strip()
        if tail:
            lines.append(tail)

        if "OUTPUT=WFN" in route_line.upper() or "OUTPUT=WFX" in route_line.upper():
            ext = "wfx" if "OUTPUT=WFX" in route_line.upper() else "wfn"
            lines.append(f"{self._wfn_filename_hint()}.{ext}")

        # Trim trailing blanks, then require exactly two trailing newlines.
        while lines and lines[-1] == "":
            lines.pop()
        content = "\n".join(lines) + "\n"

        if self.link1_enable.isChecked():
            link1_route = self.link1_route_edit.toPlainText().strip()
            if not link1_route.startswith("#"):
                link1_route = "# " + link1_route
            link1_lines = [
                "--Link1--",
                f"%chk={chk}",
            ]
            if oldchk:
                link1_lines.insert(1, f"%oldchk={oldchk}")
            link1_lines.append(f"%nprocshared={self.nproc_spin.value()}")
            link1_lines.append(self._mem_line())
            link1_lines.append(link1_route)
            link1_lines.append("")
            link1_lines.append(self.link1_title_edit.text().strip() or "Gaussian Job")
            link1_lines.append("")
            link1_lines.append(f"{charge} {mult}")

            copy_coords = "Copy coordinates" in self.link1_geom_src.currentText()
            if copy_coords:
                link1_lines.extend(coord_lines)

            link1_tail = self.link1_tail_edit.toPlainText().strip()
            if link1_tail:
                link1_lines.append("")
                link1_lines.append(link1_tail)

            while link1_lines and link1_lines[-1] == "":
                link1_lines.pop()

            content = content.rstrip("\n") + "\n\n" + "\n".join(link1_lines) + "\n"

        # Gaussian requires the file to end with a blank line.
        content = content.rstrip("\n") + "\n\n"
        return content

    # ------------------------------------------------------------------
    # Keyword builder
    # ------------------------------------------------------------------

    def open_keyword_builder(self):
        self._resolve_live_mol()
        if (
            getattr(self, "builder_dialog", None) is not None
            and self.builder_dialog is not None
        ):
            self.builder_dialog.parse_route(self.keywords_edit.toPlainText())
            self.builder_dialog.mol = self.mol
            self._load_builder_constraints()
            self.builder_dialog.store_state()
            self.builder_dialog.show()
            self.builder_dialog.raise_()
            self.builder_dialog.activateWindow()
            return

        self.builder_dialog = GaussianRouteBuilderDialog(
            self,
            self.keywords_edit.toPlainText(),
            mol=self.mol,
            main_window=self.parent(),
        )
        self._load_builder_constraints()
        self.builder_dialog.store_state()
        self.builder_dialog.finished.connect(lambda r: self.on_builder_finished(r))
        self.builder_dialog.show()

    def _load_builder_constraints(self):
        """Sync tail ModRedundant lines into the builder's constraint table."""
        try:
            _, modred = self._split_tail_modredundant(
                self.tail_edit.toPlainText()
            )
            self.builder_dialog.load_modredundant_lines(modred)
        except Exception as _e:
            logging.warning("_load_builder_constraints: %s", _e)

    def on_builder_finished(self, result):
        if result == QDialog.DialogCode.Accepted:
            if getattr(self, "builder_dialog", None) is not None:
                route = self.builder_dialog.get_route()
                self.keywords_edit.setPlainText(route)
                self._sync_modredundant_lines()
                self._auto_insert_tail_for_route(route)
        self.update_preview()

    def _auto_insert_tail_for_route(self, route):
        """Insert required tail sections implied by route keywords.

        Mirrors ORCA Pro's _auto_insert_blocks_for_route: Pop=NBORead is
        meaningless without a $NBO section after the coordinates.
        """
        route_upper = route.upper()
        current = self.tail_edit.toPlainText()
        current_upper = current.upper()

        additions = []
        if "POP=NBOREAD" in route_upper and "$NBO" not in current_upper:
            nbo = TAIL_TEMPLATES.get("NBO Analysis ($NBO)")
            if nbo:
                additions.append(nbo.rstrip("\n"))

        if not additions:
            return
        text = current.rstrip() + "\n" if current.strip() else ""
        self.tail_edit.setPlainText(text + "\n".join(additions) + "\n")

    @staticmethod
    def _split_tail_modredundant(text):
        """Split tail text into (other_lines, modredundant_lines)."""
        others = []
        modred = []
        for line in text.splitlines():
            if parse_modredundant_line(line):
                modred.append(line.strip())
            else:
                others.append(line)
        return others, modred

    def _sync_modredundant_lines(self):
        """Replace the tail's ModRedundant lines with the builder's table.

        Full sync, not append: rows removed or edited in the builder's
        Constraints/Scan tab disappear from / change in the tail too.
        Non-constraint tail content (Gen basis, $NBO, ...) is preserved.
        """
        builder = getattr(self, "builder_dialog", None)
        if builder is None:
            return
        try:
            new_lines = builder.get_modredundant_lines()
        except Exception as _e:
            logging.warning("_sync_modredundant_lines: %s", _e)
            return
        current = self.tail_edit.toPlainText()
        others, old_lines = self._split_tail_modredundant(current)
        if old_lines == new_lines:
            return
        parts = []
        other_text = "\n".join(others).rstrip()
        if other_text.strip():
            parts.append(other_text)
        if new_lines:
            parts.append("\n".join(new_lines))
        self.tail_edit.setPlainText("\n".join(parts) + "\n" if parts else "")

    # ------------------------------------------------------------------
    # Save
    # ------------------------------------------------------------------

    def save_file(self):
        coord_lines = self._get_active_coord_lines()
        if any("Error" in line for line in coord_lines):
            err = "\n".join(line for line in coord_lines if "Error" in line)
            QMessageBox.critical(self, "Error", f"Coordinate Generation Failed:\n{err}")
            return

        default_dir = os.getcwd()
        default_base = "gaussian_job.gjf"

        if self.filename:
            if os.path.isabs(self.filename):
                default_dir = os.path.dirname(self.filename)
            norm_name = self.filename.replace("\\", "/")
            base_name = norm_name.split("/")[-1]
            if base_name:
                default_base = os.path.splitext(base_name)[0]

        default_base = re.sub(r'[\\/*?:"<>|]', "_", default_base).strip()
        default_base = default_base.lstrip("_")
        if not default_base:
            default_base = "gaussian_job"
        if default_base.lower().endswith((".gjf", ".com")):
            default_base = os.path.splitext(default_base)[0]

        if getattr(self, "auto_suffix_cb", None) and self.auto_suffix_cb.isChecked():
            suffix = self._auto_suffix()
            if suffix and not default_base.endswith(suffix):
                default_base += suffix

        default_base += ".gjf"
        default_full = os.path.join(default_dir, default_base)

        file_path, _ = QFileDialog.getSaveFileName(
            self,
            "Save Gaussian Input",
            default_full,
            "Gaussian Input (*.gjf *.com);;All Files (*)",
        )

        if file_path:
            try:
                content = self.preview_text.toPlainText()
                saved_base = os.path.splitext(os.path.basename(file_path))[0]
                content = self._rewrite_chk(content, saved_base)

                with open(file_path, "w", encoding="utf-8") as f:
                    f.write(content)

                self.preview_text.setText(content)
                self.current_inp_file = file_path
                self._saved_inp_content = content
                self._update_title()
            except Exception as e:
                QMessageBox.critical(self, "Error", f"Failed to save file:\n{str(e)}")

    def _auto_suffix(self):
        kw = self.keywords_edit.toPlainText().upper()
        for suffix, matcher in _AUTO_SUFFIX_RULES:
            if matcher(kw):
                return suffix
        return ""

    @staticmethod
    def _rewrite_chk(content, base_name):
        """Rewrite every %chk= line to use the saved file's basename.

        The --Link1-- section repeats %chk so it can read Job 1's
        checkpoint; all occurrences must stay in sync with the filename.
        """
        chk_line = f"%chk={base_name}.chk"
        if re.search(r"^%chk=.*$", content, re.MULTILINE | re.IGNORECASE):
            content = re.sub(
                r"^%chk=.*$",
                chk_line,
                content,
                flags=re.MULTILINE | re.IGNORECASE,
            )
        return content

    # ------------------------------------------------------------------
    # Preset Management
    # ------------------------------------------------------------------

    def load_presets_from_file(self):
        self.presets_data = {}
        if os.path.exists(SETTINGS_FILE):
            try:
                with open(SETTINGS_FILE, "r", encoding="utf-8") as f:
                    self.presets_data = json.load(f)
            except Exception as e:
                logging.warning("Error loading presets: %s", e)

        if "Default" not in self.presets_data:
            self.presets_data["Default"] = {
                "nproc": 4,
                "mem_val": 4,
                "mem_unit": "GB",
                "chk": "",
                "oldchk": "",
                "route": "#P B3LYP/6-31G(d) EmpiricalDispersion=GD3BJ Opt Freq",
                "tail": "",
                "link1_enabled": False,
                "link1_route": "#P B3LYP/6-31G(d) Freq Geom=Check Guess=Read",
                "link1_title": "Generated by MoleditPy Gaussian Input Generator Pro Plugin",
                "link1_geom_src": "Checkpoint (Geom=Check Guess=Read)",
                "link1_tail": "",
                "coord_format": "Cartesian (XYZ)",
            }

        if "Global" in self.presets_data:
            global_cfg = self.presets_data["Global"]
            if hasattr(self, "auto_suffix_cb") and "auto_suffix" in global_cfg:
                self.auto_suffix_cb.setChecked(global_cfg["auto_suffix"])

        self.update_preset_combo()

    def update_preset_combo(self):
        current = self.preset_combo.currentText()
        self.preset_combo.blockSignals(True)
        self.preset_combo.clear()

        keys = [k for k in self.presets_data.keys() if k != "Global"]
        self.preset_combo.addItems(sorted(keys))
        if current in self.presets_data:
            self.preset_combo.setCurrentText(current)
        elif "Default" in self.presets_data:
            self.preset_combo.setCurrentText("Default")
        self.preset_combo.blockSignals(False)
        self.apply_selected_preset()

    def apply_selected_preset(self):
        name = self.preset_combo.currentText()
        if name not in self.presets_data:
            return
        data = self.presets_data[name]
        self.nproc_spin.setValue(data.get("nproc", 4))
        self.mem_spin.setValue(data.get("mem_val", 4))
        self.mem_unit.setCurrentText(data.get("mem_unit", "GB"))
        self.chk_edit.setText(data.get("chk", ""))
        self.oldchk_edit.setText(data.get("oldchk", ""))
        self.keywords_edit.setText(
            data.get("route", "#P B3LYP/6-31G(d) EmpiricalDispersion=GD3BJ Opt Freq")
        )
        self.tail_edit.setPlainText(data.get("tail", ""))
        self.link1_enable.setChecked(data.get("link1_enabled", False))
        self.link1_route_edit.setPlainText(
            data.get("link1_route", "#P B3LYP/6-31G(d) Freq Geom=Check Guess=Read")
        )
        self.link1_title_edit.setText(
            data.get(
                "link1_title",
                "Generated by MoleditPy Gaussian Input Generator Pro Plugin",
            )
        )
        src = data.get("link1_geom_src", "")
        if src:
            self.link1_geom_src.setCurrentText(src)
        self.link1_tail_edit.setPlainText(data.get("link1_tail", ""))
        self.coord_format_combo.setCurrentText(
            data.get("coord_format", "Cartesian (XYZ)")
        )
        self._update_link1_ui()
        self.update_preview()

    def save_preset_dialog(self):
        name, ok = QInputDialog.getText(self, "Save Preset", "Preset Name:")
        if ok and name:
            self.presets_data[name] = {
                "nproc": self.nproc_spin.value(),
                "mem_val": self.mem_spin.value(),
                "mem_unit": self.mem_unit.currentText(),
                "chk": self.chk_edit.text(),
                "oldchk": self.oldchk_edit.text(),
                "route": self.keywords_edit.toPlainText(),
                "tail": self.tail_edit.toPlainText(),
                "link1_enabled": self.link1_enable.isChecked(),
                "link1_route": self.link1_route_edit.toPlainText(),
                "link1_title": self.link1_title_edit.text(),
                "link1_geom_src": self.link1_geom_src.currentText(),
                "link1_tail": self.link1_tail_edit.toPlainText(),
                "coord_format": self.coord_format_combo.currentText(),
            }
            self.save_presets_to_file()
            self.update_preset_combo()
            self.preset_combo.setCurrentText(name)

    def delete_preset(self):
        name = self.preset_combo.currentText()
        if name == "Default":
            QMessageBox.warning(self, "Warning", "Cannot delete Default preset.")
            return
        confirm = QMessageBox.question(self, "Confirm", f"Delete preset '{name}'?")
        if confirm == QMessageBox.StandardButton.Yes:
            del self.presets_data[name]
            self.save_presets_to_file()
            self.update_preset_combo()

    def save_presets_to_file(self):
        try:
            with open(SETTINGS_FILE, "w", encoding="utf-8") as f:
                json.dump(self.presets_data, f, indent=4)
        except OSError as e:
            QMessageBox.warning(self, "Error", f"Failed to save presets: {e}")

    def save_global_settings(self):
        if not getattr(self, "ui_ready", False):
            return
        if not hasattr(self, "presets_data"):
            self.presets_data = {}
        if "Global" not in self.presets_data:
            self.presets_data["Global"] = {}
        if hasattr(self, "auto_suffix_cb"):
            self.presets_data["Global"]["auto_suffix"] = self.auto_suffix_cb.isChecked()
        self.save_presets_to_file()

    # ------------------------------------------------------------------
    # Charge/Mult Logic
    # ------------------------------------------------------------------

    def calc_initial_charge_mult(self):
        if not self._resolve_live_mol():
            return
        try:
            try:
                charge = Chem.GetFormalCharge(self.mol)
            except Exception:
                charge = 0
            num_radical = sum(
                atom.GetNumRadicalElectrons() for atom in self.mol.GetAtoms()
            )
            mult = num_radical + 1
            self.charge_spin.setValue(int(charge))
            self.mult_spin.setValue(int(mult))
            self.validate_charge_mult()
        except Exception as _e:
            logging.warning("calc_initial_charge_mult failed: %s", _e)

    def validate_charge_mult(self):
        if not self._resolve_live_mol():
            return
        try:
            charge = self.charge_spin.value()
            mult = self.mult_spin.value()
            total_protons = sum(atom.GetAtomicNum() for atom in self.mol.GetAtoms())
            total_electrons = total_protons - charge
            is_valid = (total_electrons % 2 == 0 and mult % 2 != 0) or (
                total_electrons % 2 != 0 and mult % 2 == 0
            )
            if is_valid:
                self.charge_spin.setPalette(self.default_palette)
                self.mult_spin.setPalette(self.default_palette)
            else:
                p = self.charge_spin.palette()
                p.setColor(QPalette.ColorRole.Base, QColor("#FFDDDD"))
                p.setColor(QPalette.ColorRole.Text, Qt.GlobalColor.red)
                self.charge_spin.setPalette(p)
                self.mult_spin.setPalette(p)
            self.update_preview()
        except Exception as _e:
            logging.warning("validate_charge_mult failed: %s", _e)

    # ------------------------------------------------------------------
    # Window lifecycle
    # ------------------------------------------------------------------

    def closeEvent(self, event):
        if getattr(self, "builder_dialog", None) is not None and self.builder_dialog:
            self.builder_dialog.close()
        if self.current_inp_file and self._is_modified():
            name = os.path.basename(self.current_inp_file)
            reply = QMessageBox.question(
                self,
                "Unsaved Changes",
                f'Save changes to "{name}"?',
                QMessageBox.StandardButton.Save
                | QMessageBox.StandardButton.Discard
                | QMessageBox.StandardButton.Cancel,
            )
            if reply == QMessageBox.StandardButton.Save:
                self._save_current_file()
                if self._is_modified():
                    event.ignore()
                    return
            elif reply == QMessageBox.StandardButton.Cancel:
                event.ignore()
                return
        super().closeEvent(event)

    def _is_modified(self):
        if self.current_inp_file is None or self._saved_inp_content is None:
            return False
        return self.preview_text.toPlainText() != self._saved_inp_content

    def _update_title(self):
        base = f"{PLUGIN_NAME} v{PLUGIN_VERSION}"
        if self.current_inp_file:
            name = os.path.basename(self.current_inp_file)
            dirty = " *" if self._is_modified() else ""
            self.setWindowTitle(f"{name}{dirty} — {base}")
        else:
            self.setWindowTitle(f"{base} *")

    def _save_current_file(self):
        if not self.current_inp_file:
            return
        try:
            saved_base = os.path.splitext(os.path.basename(self.current_inp_file))[0]
            content = self._rewrite_chk(self.preview_text.toPlainText(), saved_base)
            with open(self.current_inp_file, "w", encoding="utf-8") as f:
                f.write(content)
            self.preview_text.setText(content)
            self._saved_inp_content = content
            self._current_content = content
            self._update_title()
        except Exception as e:
            QMessageBox.critical(self, "Save Error", f"Could not save file:\n{e}")

    def _on_ctrl_s(self):
        if self.current_inp_file:
            self._save_current_file()
        else:
            self.save_file()

    def accept(self):
        if getattr(self, "builder_dialog", None) is not None and self.builder_dialog:
            self.builder_dialog.close()
        super().accept()

    def reject(self):
        if getattr(self, "builder_dialog", None) is not None and self.builder_dialog:
            self.builder_dialog.close()
        super().reject()

    def keyPressEvent(self, event):
        if event.key() == Qt.Key.Key_Escape:
            focused = self.focusWidget()
            if isinstance(focused, (QLineEdit, QComboBox, QSpinBox, QTextEdit)):
                focused.clearFocus()
                return
        super().keyPressEvent(event)
